sudo: required
dist: focal
language: node_js
env:
  - CXX="g++-4.9"
node_js:
  - "16"
  - "12"
  - "11"


addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - gcc-4.9
